THESE SHOULD BE METHODS INSIDE OF THE NPC CLASS

class NPC_type

def npc_gen_guard(self, sex = Male, p_level)
	guard rank
		guards clothing and armours
		guards weapons
	all have some gold
		leutenants and up have a bag of gold
	all guards are male
	all guards will end up on the lawful side of alignment
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [medium,LARGE,fit,athletic,bodybuilder]
	# random gen for armour list
	armour.head =[gurads helmet, none]
	armour.neck =[dog_tags]
	armour.chest =[]
	armour.torso =[]
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = [Leather_boots_brown, ]
	
def local_magistrate_guards(self, sex, p_level)
	all guards will end up on the lawful side of alignment
	age range shifted to older
	better stats than guards
	better equipment than guards
	higher skilled than guards
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [medium,LARGE,fit,athletic,bodybuilder]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []
	
def npc_gen_tradesman(self, sex, P-level)
	mostly male
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_bandit(self, sex, P_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_theif(self, sex, p_level)
	if sex no specified select randomly
	usually have lockpicks
	usually have quiet 
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []
	
def npc_gen_bount_hunter(self, sex, p_level)
	they are either looking for you or a person, that person may be wanted
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []
	
def npc_gen_sea_captain(self, sex, p_level)
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_adventurer(self, sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_trader(self, sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_master_fighter(self,sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_villian(self, sex, p_level)
	always has a neutral to evil alignment, can randomly select then use that to base a few other attributes
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_master_craftsman(self, sex, p_level)
	the sex may also dictate what trade
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_master_trader(self, sex, p_level)
	a master trader will have more gold on hand, and better items,he may also have a quest and a very nice item or artifact for a reward
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_fisherman(self, sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_commoner(self, sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []
	
def npc_gen_outlaw(self, sex, p_level)
	if sex no specified select randomly	
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def npc_gen_not_so_commoner(self, sex, p_level)
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []
	
def npc_gen_misc(self, sex, p_level)
	if sex no specified select randomly
	guard in common clothing - incognito
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [tall and lanky, medium, athletic, fit, bodybuilder, LARGE, heavy set, overweight]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

def gen_npc_child(self, sex, level = 1)
	this player not intended for combat
	if sex no specified select randomly
	stats = dict{str:L-H,dex:L-H,con:L-H,int:L-H,wis:L-H,chr:L-H}
	frame_size = [child]
	armour.head = []
	armour.neck = []
	armour.chest = []
	armour.torso = []
	armour.left.upper_arm = []
	armour.right.upper_arm = []
	armour.left.forearm = []
	armour.right forearm = []
	armour.left.wrist = []
	armour.right.wrist = []
	armour.left.hand = []
	armour.right.hand = []
	armour.left.fingers = []
	armour.right.fingers = []
	armour.belt = []
	armour.pants = []
	armour.left.upper_leg = []
	armour.right.upper_leg = []
	armour.left.lower_leg = []
	armour.right.lower_leg = []
	armour.feet = []

